import Alligator from "./models/Alligator.js";
import Bear from "./models/Bear.js";
import Cat from "./models/Cat.js";
import Dog from "./models/Dog.js";
import Elephant from "./models/Elephant.js";
import Fox from "./models/Fox.js";
import Gorilla from "./models/Gorilla.js";
import Hawk from "./models/Hawk.js";
import Iguana from "./models/Iguana.js";
import Jackyl from "./models/Jackyl.js";
import Kangaroo from "./models/Kangaroo.js";
import Lion from "./models/Lion.js";
import Meerkat from "./models/Meerkat.js";
import Narwahl from "./models/Narwahl.js";
import Octopus from "./models/Octopus.js";
import Peacock from "./models/Peacock.js";
import Quail from "./models/Quail.js";
import Rhino from "./models/Rhino.js";
import Snake from "./models/Snake.js";
import Tiger from "./Models/Tiger.js";
import Urchin from "./models/Urchin.js";
import Vulture from "./models/Vulture.js";
import Wolf from "./models/Wolf.js";
import Xerus from "./models/Xerus.js";
import Yak from "./models/Yak.js";
import Zebra from "./models/Zebra.js";

let ally = new Alligator("Ally", "female");
let bailey = new Bear("Bailey", "male");
let felix = new Cat("Felix", "male");
let spot = new Dog("Spot", "female");
let dumbo = new Elephant("Dumbo", "male");
let finn = new Fox("Finn", "male");
let gobo = new Gorilla("Gobo", "female");
let hera = new Hawk("Hera", "female");
let iggy = new Iguana("Iggy", "male");
let jim = new Jackyl("Jim", "male");
let hops = new Kangaroo("Hops", "male");
let laura = new Lion("Laura", "female");
let maurice = new Meerkat("Maurice", "male");
let nelson = new Narwahl("Nelson", "female");
let olive = new Octopus("Olive", "female");
let pitri = new Peacock("Pitri", "male");
let quinn = new Quail("Quinn", "female");
let rocco = new Rhino("Rocco", "male");
let sid = new Snake("Sid", "male");
let terri = new Tiger("Terri", "female");
let uma = new Urchin("Uma", "female");
let vicky = new Vulture("Vicky", "female");
let willis = new Wolf("Willis", "male");
let xerxes = new Xerus("Xerxes", "male");
let yaddle = new Yak("Yaddle", "female");
let zero = new Zebra("Zero", "male");